# Generated by Django 3.0.7 on 2020-06-29 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_name', models.CharField(max_length=21)),
                ('counter_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_day', models.CharField(max_length=12)),
                ('event_sect', models.CharField(max_length=10)),
                ('event_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBasic',
            fields=[
                ('id_num', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=21)),
                ('last_name', models.CharField(max_length=21)),
                ('dob', models.DateField(blank=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrLevel',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attendance_tracker.StudentBasic')),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_one', models.BooleanField(default=False, verbose_name='1st Grade')),
                ('is_two', models.BooleanField(default=False, verbose_name='2nd Grade')),
                ('is_three', models.BooleanField(default=False, verbose_name='3rd Grade')),
                ('is_four', models.BooleanField(default=False, verbose_name='4th Grade')),
                ('is_five', models.BooleanField(default=False, verbose_name='5th Grade')),
                ('is_six', models.BooleanField(default=False, verbose_name='6th Grade')),
                ('is_seven', models.BooleanField(default=False, verbose_name='7th Grade')),
                ('is_eight', models.BooleanField(default=False, verbose_name='8th Grade')),
                ('is_nine', models.BooleanField(default=False, verbose_name='9th Grade')),
                ('is_ten', models.BooleanField(default=False, verbose_name='10th Grade')),
                ('is_eleven', models.BooleanField(default=False, verbose_name='11th Grade')),
                ('is_tewelve', models.BooleanField(default=False, verbose_name='12th Grade')),
                ('is_beyond', models.BooleanField(default=False, verbose_name='College and Graduates')),
                ('license', models.CharField(choices=[('NoLi', 'No License'), ('Standard', 'Standard License'), ('Professional', 'Professional License'), ('Ultimate', 'Ultimate License')], max_length=13)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCntInf',
            fields=[
                ('student_grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attendance_tracker.StudentGrLevel')),
                ('address', models.CharField(blank=True, max_length=225)),
                ('city', models.CharField(max_length=48)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('personal_cell', models.CharField(blank=True, max_length=17)),
                ('father_cell', models.CharField(blank=True, max_length=17)),
                ('mother_cell', models.CharField(blank=True, max_length=17)),
                ('parent_email', models.EmailField(blank=True, help_text='Parent email', max_length=254)),
                ('student_email', models.EmailField(blank=True, help_text='Parent email', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.NullBooleanField()),
                ('event_idn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='attendance_tracker.Events')),
                ('student_idn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_tracker.StudentGrLevel')),
            ],
        ),
    ]
