# Generated by Django 3.0.7 on 2020-06-30 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_day',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_sect',
            field=models.CharField(choices=[('Mor', 'Morning'), ('Aft', 'Afternoon'), ('Eve', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('SundaySchool', 'Sunday School'), ('FieldTrip', 'Field Trip'), ('Mahragan', 'Mahragan'), ('GameDay', 'Game Day'), ('Theater', 'Theater'), ('Choir', 'Choir'), ('Hymns', 'Hymns'), ('Coptic', 'Coptic'), ('Filming', 'Filming'), ('Performance', 'Performance'), ('Practice', 'Practice'), ('Scout-Boys', 'Scout - Boys'), ('Scout-Girls', 'Scout - Girls'), ('Scount-Gen', 'Scout General'), ('Sports', 'Sports'), ('Club', 'Club'), ('Other', 'Other')], max_length=70),
        ),
        migrations.AlterField(
            model_name='studentbasic',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentcntinf',
            name='address',
            field=models.CharField(blank=True, default='No Address Exists', max_length=225),
        ),
        migrations.AlterField(
            model_name='studentcntinf',
            name='father_cell',
            field=models.CharField(blank=True, default='No Phone Number', max_length=17),
        ),
        migrations.AlterField(
            model_name='studentcntinf',
            name='mother_cell',
            field=models.CharField(blank=True, default='No Phone Number', max_length=17),
        ),
        migrations.AlterField(
            model_name='studentcntinf',
            name='parent_email',
            field=models.EmailField(blank=True, default='temp-dne@temp.com', help_text='Parent email', max_length=254),
        ),
        migrations.AlterField(
            model_name='studentcntinf',
            name='personal_cell',
            field=models.CharField(blank=True, default='No Phone Number', max_length=17),
        ),
        migrations.AlterField(
            model_name='studentcntinf',
            name='student_email',
            field=models.EmailField(blank=True, default='temp-dne@temp.com', help_text='Student email', max_length=254),
        ),
    ]
