# Generated by Django 3.0.7 on 2020-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0002_auto_20200630_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_sect',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('Liturgy', 'Liturgy'), ('Bible Study', 'Bible Study'), ('Sunday School', 'Sunday School'), ('Field Trip', 'Field Trip'), ('Mahragan', 'Mahragan'), ('GameDay', 'Game Day'), ('Theater', 'Theater'), ('Choir', 'Choir'), ('Hymns', 'Hymns'), ('Coptic', 'Coptic'), ('Filming', 'Filming'), ('Performance', 'Performance'), ('Practice', 'Practice'), ('Scout-Boys', 'Scout - Boys'), ('Scout-Girls', 'Scout - Girls'), ('Scount-Gen', 'Scout General'), ('Sports', 'Sports'), ('Club', 'Club'), ('Holy Week', 'Holy Week'), ('Special Church Event', 'Special Church Event'), ('Other', 'Other')], max_length=70),
        ),
        migrations.AlterField(
            model_name='studentattn',
            name='present',
            field=models.NullBooleanField(default=False),
        ),
    ]
