# Generated by Django 3.0.7 on 2020-07-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0004_auto_20200701_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_day',
        ),
    ]
