# Generated by Django 3.0.7 on 2020-07-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0005_remove_events_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
