# Generated by Django 3.0.7 on 2020-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0006_events_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_day',
            field=models.CharField(default='No Day', max_length=20, null=True),
        ),
    ]
