# Generated by Django 3.0.7 on 2020-07-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0007_auto_20200706_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='assignees',
            field=models.ManyToManyField(related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_day',
            field=models.CharField(default='Day of Week', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_sect',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('Liturgy', 'Liturgy'), ('Bible Study', 'Bible Study'), ('Sunday School', 'Sunday School'), ('Field Trip', 'Field Trip'), ('Mahragan', 'Mahragan'), ('GameDay', 'Game Day'), ('Theater', 'Theater'), ('Choir', 'Choir'), ('Hymns', 'Hymns'), ('Coptic', 'Coptic'), ('Filming', 'Filming'), ('Performance', 'Performance'), ('Practice', 'Practice'), ('Scout-Boys', 'Scout - Boys'), ('Scout-Girls', 'Scout - Girls'), ('Scount-Gen', 'Scout General'), ('Sports', 'Sports'), ('Club', 'Club'), ('Holy Week', 'Holy Week'), ('Special Church Event', 'Special Church Event'), ('Other', 'Other')], default='Sunday School', max_length=70),
        ),
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
