# Generated by Django 3.0.7 on 2020-07-07 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0008_auto_20200707_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='assignees',
            field=models.ManyToManyField(related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
