# Generated by Django 3.0.7 on 2020-07-08 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0009_auto_20200707_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='assigned_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
