# Generated by Django 3.0.7 on 2020-07-08 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tracker', '0010_events_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='assigned_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
